import type { ReactNode } from 'react';
import {
  AccountBookOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  CreditCardOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DesktopOutlined,
  ExperimentOutlined,
  FileTextOutlined,
  FundOutlined,
  FundViewOutlined,
  GlobalOutlined,
  HomeOutlined,
  KeyOutlined,
  LockOutlined,
  MoneyCollectOutlined,
  OrderedListOutlined,
  PayCircleOutlined,
  PrinterOutlined,
  ProfileOutlined,
  RollbackOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SettingOutlined,
  StopOutlined,
  SwapOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  UnlockOutlined,
  UserAddOutlined,
  UserOutlined,
  WalletOutlined,
} from '@ant-design/icons';

/** 菜单图标名 → 组件映射（后端 menus.icon 为字符串图标名，未匹配回退 AppstoreOutlined） */
export const ICON_MAP: Record<string, React.ComponentType> = {
  AppstoreOutlined,
  DashboardOutlined,
  DesktopOutlined,
  HomeOutlined,
  BankOutlined,
  UserOutlined,
  UserAddOutlined,
  TeamOutlined,
  SafetyOutlined,
  SafetyCertificateOutlined,
  PayCircleOutlined,
  MoneyCollectOutlined,
  AccountBookOutlined,
  CreditCardOutlined,
  WalletOutlined,
  SwapOutlined,
  FundViewOutlined,
  FundOutlined,
  AuditOutlined,
  FileTextOutlined,
  PrinterOutlined,
  ProfileOutlined,
  SettingOutlined,
  ToolOutlined,
  DatabaseOutlined,
  ScheduleOutlined,
  RollbackOutlined,
  StopOutlined,
  LockOutlined,
  UnlockOutlined,
  KeyOutlined,
  ThunderboltOutlined,
  ExperimentOutlined,
  GlobalOutlined,
  OrderedListOutlined,
};

export function menuIcon(name?: string | null): ReactNode {
  const Icon = (name && ICON_MAP[name]) || AppstoreOutlined;
  return <Icon />;
}
