server:
  port: 7700
spring:
  application:
    name: air-bank-core
  config:
    import:
      - nacos:${spring.application.name}.properties?group=DEFAULT_GROUP
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        enabled: true