<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.airbank</groupId>
    <artifactId>airbank</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>AirBank</name>
    <description>AirBank 分布式模拟银行系统</description>

    <modules>
        <module>airbank-dependencies</module>
        <module>airbank-common</module>
        <module>airbank-api</module>
        <module>airbank-gateway</module>
        <module>airbank-uam</module>
        <module>airbank-core</module>
        <module>airbank-wealth</module>
        <module>airbank-loan</module>
        <module>airbank-counter</module>
        <module>airbank-ebank</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.release>17</maven.compiler.release>
        <!-- Spring 6.1 要求：保留方法参数名（@RequestParam 无显式 name 时依赖反射读取） -->
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <airbank.version>1.0.0</airbank.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.airbank</groupId>
                <artifactId>airbank-dependencies</artifactId>
                <version>${airbank.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>3.2.10</version>
                    <executions>
                        <execution>
                            <goals><goal>repackage</goal></goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.2.5</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
