version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v3.0.2
    container_name: nacos
    restart: always
    environment:
      # 单机模式
      - MODE=standalone
      # - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=nYP2R9hEHfNI5EKLC4RRbhdrOBpiEPh7vLcxIsvTpVk27u3ncuWtRS+L0yENvorEBm66Fyv1J8XihM2sg4X47w==
      - NACOS_AUTH_IDENTITY_KEY=233eaec3ea929c3ebbab93244b398855
      - NACOS_AUTH_IDENTITY_VALUE=d69762888570122b1e53d237d02dcada7d437fb11013ada3c0cd1228c67debd6
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - nacos_data:/home/nacos/data
      - nacos_logs:/home/nacos/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/console/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  nacos_data:
    driver: local
  nacos_logs:
    driver: local

networks:
  default:
    name: nacos-network