/** IPC 通道名常量：主进程 ipcMain.handle 与 preload 封装共用。 */
export const Ipc = {
  appInfo: 'app:info',
  appQuit: 'app:quit',
  bootState: 'app:boot-state',
  settingsGet: 'settings:get',
  settingsPatch: 'settings:patch',
  setupRun: 'setup:run',
  setupSnapshot: 'setup:snapshot',
  serverStatus: 'server:status',
  serverStart: 'server:start',
  serverStop: 'server:stop',
  serverRestart: 'server:restart',
  runtimeStatus: 'runtime:status',
  runtimeInstall: 'runtime:install',
  kernelStatus: 'kernel:status',
  kernelInstall: 'kernel:install',
  kernelCores: 'kernel:cores',
  kernelActivateCore: 'kernel:activate-core',
  kernelRemoveCore: 'kernel:remove-core',
  kernelLatestVersion: 'kernel:latest-version',
  profilesList: 'profiles:list',
  profilesCreate: 'profiles:create',
  profilesRemove: 'profiles:remove',
  profilesActivate: 'profiles:activate',
  pluginsList: 'plugins:list',
  pluginsAdd: 'plugins:add',
  pluginsRemove: 'plugins:remove',
  logsGet: 'logs:get',
  logsClear: 'logs:clear',
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',
  shellOpenExternal: 'shell:open-external',
  shellShowItem: 'shell:show-item',
} as const

/** 主进程 → 渲染层广播事件通道。 */
export const Events = {
  serverStatus: 'event:server-status',
  log: 'event:log',
  installPlan: 'event:install-plan',
  kernelChanged: 'event:kernel-changed',
  runtimeChanged: 'event:runtime-changed',
  settingsChanged: 'event:settings-changed',
  nativeTheme: 'event:native-theme',
  menuReloadWebview: 'menu:reload-webview',
} as const
